Update docker-compose.yml

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -1,50 +1,99 @@
-services:
-  app:
-    stdin_open: true
-    tty: true
-    image: container-icdfwsy
-    build:
-      context: ./src
-    ports:
-      - "5000:5000"
-    volumes:
-      - type: bind
-        source: ./src/web
-        target: /usr/src/app
-    environment:
-      ALLOWED_HOSTS: "127.0.0.1,localhost"
-      DATABASE_URL: mysql2=//app_user=password@db=3306/app_database?pool=5&useUnicode=true&characterEncoding=UTF-8
-      DB_ENGINE: django.db.backends.mysql
-      DB_HOST: db
-      DB_NAME: app_database
-      DB_PASSWORD: password
-      DB_PORT: 3306
-      DB_USER: app_user
-      DEBUG: "True"
-      SECRET_KEY: local_development
+#!/bin/bash
 
+set -e
+set -u
 
-  db:
-    # This database service is used only for local development
-    # Note: It may be preferable to use an online database service
-    # https://db.anotherwebservice.com/
-    image: mysql
-    restart: always
-    environment:
-      MYSQL_ROOT_PASSWORD: password
-      MYSQL_USER: app_user
-      MYSQL_PASSWORD: password
-      MYSQL_DATABASE: app_database
+image=$1
+architecture=$2
+mirror=${3:-http://http.kali.org/kali}
 
-  phpmyadmin:
-    # To view the database during local development
-    # Visit http://127.0.0.1:8080/
-    # Server is: db
-    # Username is same as MYSQL_USER
-    # Password is same as MYSQL_PASSWORD
-    image: phpmyadmin
-    restart: always
-    ports:
-      - 8080:80
-    environment:
-      PMA_ARBITRARY: "1"
+rootfsDir=rootfs-$image-$architecture
+tarball=$image-$architecture.tar.gz
+versionFile=$image-$architecture.release.version
+
+rootfs_chroot() {
+    PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' \
+        chroot "$rootfsDir" "$@"
+}
+
+case $image in
+    kali-dev|kali-rolling)
+        distro=$image
+        ;;
+    kali-last-release)
+        distro=kali-last-snapshot
+        ;;
+    *)
+        echo "ERROR: unsupported image '$image'" >&2
+        exit 1
+        ;;
+esac
+
+if [ ! -e /usr/share/debootstrap/scripts/"$distro" ]; then
+    echo "ERROR: debootstrap has no script for $distro" >&2
+    echo "ERROR: use a newer debootstrap" >&2
+    exit 1
+fi
+
+if [ ! -e /usr/share/keyrings/kali-archive-keyring.gpg ]; then
+    echo "ERROR: you need /usr/share/keyrings/kali-archive-keyring.gpg" >&2
+    echo "ERROR: install kali-archive-keyring" >&2
+    exit 1
+fi
+
+rm -rf "$rootfsDir" "$tarball"
+
+ret=0
+debootstrap --variant=minbase --components=main,contrib,non-free,non-free-firmware \
+    --arch="$architecture" --include=kali-archive-keyring \
+    "$distro" "$rootfsDir" "$mirror" || ret=$?
+if [ $ret != 0 ]; then
+    [ -e "$rootfsDir"/debootstrap/debootstrap.log ] && \
+        tail -v "$rootfsDir"/debootstrap/debootstrap.log
+    exit $ret
+fi
+
+rootfs_chroot apt-get -y --no-install-recommends install kali-defaults
+
+rootfs_chroot apt-get clean
+
+# Inspired by /usr/share/docker.io/contrib/mkimage/debootstrap
+cat > "$rootfsDir/usr/sbin/policy-rc.d" <<-'EOF'
+	#!/bin/sh
+	exit 101
+EOF
+chmod +x "$rootfsDir/usr/sbin/policy-rc.d"
+
+echo 'force-unsafe-io' > "$rootfsDir"/etc/dpkg/dpkg.cfg.d/docker-apt-speedup
+
+aptGetClean='"rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true";'
+cat > "$rootfsDir"/etc/apt/apt.conf.d/docker-clean <<-EOF
+	DPkg::Post-Invoke { ${aptGetClean} };
+
+	Dir::Cache::pkgcache "";
+	Dir::Cache::srcpkgcache "";
+EOF
+
+echo 'Acquire::Languages "none";' >"$rootfsDir"/etc/apt/apt.conf.d/docker-no-languages
+
+cat > "$rootfsDir"/etc/apt/apt.conf.d/docker-gzip-indexes <<-'EOF'
+	Acquire::GzipIndexes "true";
+	Acquire::CompressionTypes::Order:: "gz";
+EOF
+
+echo 'Apt::AutoRemove::SuggestsImportant "false";' >"$rootfsDir"/etc/apt/apt.conf.d/docker-autoremove-suggests
+
+rm -f "$rootfsDir"/var/cache/ldconfig/aux-cache
+rm -rf "$rootfsDir"/var/lib/apt/lists/*
+mkdir -p "$rootfsDir"/var/lib/apt/lists/partial
+find "$rootfsDir"/var/log -depth -type f -print0 | xargs -0 truncate -s 0
+
+# https://github.com/debuerreotype/debuerreotype/pull/32
+rmdir "$rootfsDir/run/mount" 2>/dev/null || :
+
+echo "Creating $tarball"
+tar -C "$rootfsDir" --exclude "./dev/**" -pczf "$tarball" .
+
+if [ "$image" = "kali-last-release" ]; then
+    (. "$rootfsDir"/etc/os-release && echo "$VERSION") > "$versionFile"
+fi
